name: Unzip and deploy

on:
  push:
    paths:
      - 'o.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unzip archive
        run: |
          unzip o.zip -d .
          rm o.zip
      - name: Commit unpacked files
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Unpacked archive"
          git push
